import json
from pathlib import Path

def export_alpha_to_strategy_prompt(json_path: str, output_path: str):
    with open(json_path, 'r') as f:
        alpha_data = json.load(f)
        
    prompt_template = f"""
    # Automated Strategy Generation Directive
    Based on the following quant alpha metrics generated by HKUDS/Vibe-Trading:
    - Target Asset: {alpha_data.get('asset', 'MON/USDC')}
    - Factor Strategy: {alpha_data.get('strategy_name', 'Momentum')}
    - Expected Sharpe: {alpha_data.get('sharpe', 1.8)}
    
    Please write a production-ready Freqtrade Strategy class in Python implementing these exact entry and exit conditions.
    """
    
    Path(output_path).write_text(prompt_template)
    print(f"Exported Claude Code prompt template to {output_path}")

if __name__ == "__main__":
    # Example mock trigger
    pass
